apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ps-cron
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          containers:
            - name: app
              image: busybox
              command: ["ps",  "aux"]
          restartPolicy: Never