apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: application
      stage: dev
  template:
    metadata:
      labels:
        name: application
        stage: dev
    spec:
      containers:
        - name: application
          image: containous/whoami:v1.4.0
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/upload/
              name: my-storage
      volumes:
        - name: my-storage
          persistentVolumeClaim:
              claimName: my-claim