apiVersion: v1
kind: Service
metadata:
  name:  my-app-service
spec:
  selector:
    app:  my-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: my-app-service
              servicePort: 80
              