apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    name: application
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: application-service-public
spec:
  selector:
    name: application
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
