apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.public_port }}
      targetPort: 80