apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-statefulset
spec:
  replicas: 3
  serviceName: application
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: application
      stage: dev
  template:
    metadata:
      labels:
        name: application
        stage: dev
    spec:
      containers:
        - name: application
          image: nginx
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: data
              mountPath: /tmp
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nfs"
        resources:
          requests:
            storage: 200Mi
