apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      name: application
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: containous/whoami
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "32Mi"
#              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "125m"
