apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  containers:
    - name: application
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
        - containerPort: 8080
