kind: ConfigMap
apiVersion: v1
metadata:
    name: {{ .Release.Name }}-configmap
data:
    database_user: {{ .Values.database.user }}
    database_name: {{ .Values.database.name }}
    database_host: {{ .Release.Name }}-mysql-service
