apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    name: mysql
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ghost-service-public
spec:
  selector:
    name: ghost
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 2368
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ .Release.Name }}.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-ghost-service-public
              servicePort: 80
            path: /
